name: Build Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
   
    - name: Build & push Docker image 
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: robertd/alpine-aws-cdk
        tags: ${GITHUB_REF##*/}, latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
